sudo: false
language: go
git:
    depth: 1
install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
script:
    ‐ hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: BalusChen/BalusChen.github.io
    fqdn: <custom-domain-if-needed>
    target_branch: master
    email: balus@foxmail.com
    name: BalusChen
